# Generated by Django 5.1.4 on 2025-08-13 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='milkman',
            old_name='addressline1',
            new_name='addressline',
        ),
        migrations.AddField(
            model_name='milkman',
            name='joined',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='milkman',
            name='milktype',
            field=models.CharField(default='Buffalow', max_length=20),
        ),
        migrations.AddField(
            model_name='milkman',
            name='price_per_liter',
            field=models.IntegerField(default=50),
        ),
    ]
