# Generated by Django 5.1.4 on 2025-08-13 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0002_rename_addressline1_milkman_addressline_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Costumer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('phone', models.CharField(max_length=15)),
                ('addressline', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('city', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('pic', models.FileField(blank=True, default=None, null=True, upload_to=' castumer_images')),
                ('joined', models.DateField(auto_now=True)),
                ('costumer_milkman', models.CharField(max_length=50)),
                ('quantiy_liter', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Dairyimages',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('milkman_username', models.CharField(max_length=40)),
                ('pic1', models.ImageField(blank=True, default=None, null=True, upload_to='dairy')),
                ('pic2', models.ImageField(blank=True, default=None, null=True, upload_to='dairy')),
                ('pic3', models.ImageField(blank=True, default=None, null=True, upload_to='dairy')),
                ('pic4', models.ImageField(blank=True, default=None, null=True, upload_to='dairy')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('milkmanuser', models.CharField(max_length=40)),
                ('customeruser', models.CharField(max_length=40)),
                ('value', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('review', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
