# Generated by Django 5.1.4 on 2025-08-14 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0003_costumer_dairyimages_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('milkman_username', models.CharField(max_length=50)),
                ('customer_username', models.CharField(max_length=50)),
                ('delivered_qty', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('extra_qty', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('status', models.CharField(default='Delivered', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
