# Generated by Django 5.1.4 on 2025-08-17 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0005_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyrecord',
            name='amount',
        ),
    ]
