# Generated by Django 5.1.4 on 2025-08-18 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0006_remove_dailyrecord_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyrecord',
            name='custumer_status',
            field=models.CharField(default='Notupdated', max_length=30),
        ),
    ]
