# Generated by Django 5.1.4 on 2025-08-19 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0007_dailyrecord_custumer_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Extra_Milk_Today',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('milkman_username', models.CharField(max_length=30)),
                ('milkman_name', models.CharField(max_length=30)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=5)),
                ('amount', models.IntegerField()),
                ('animal_type', models.CharField(choices=[('cow', 'Cow'), ('buffalo', 'Buffalo'), ('both', 'Both')], max_length=40)),
            ],
        ),
    ]
