# Generated by Django 5.1.4 on 2025-08-19 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0008_extra_milk_today'),
    ]

    operations = [
        migrations.AddField(
            model_name='extra_milk_today',
            name='status',
            field=models.CharField(choices=[('stock', 'Stock'), ('out of stock', 'out of stock')], default='stock', max_length=30),
        ),
    ]
