# Generated by Django 5.1.4 on 2025-08-19 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0009_extra_milk_today_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='costumer',
            name='custumer_request',
            field=models.CharField(choices=[('Accept', 'Acept'), ('Reject', 'Reject')], default='Pending', max_length=30),
        ),
    ]
