# Generated by Django 5.1.4 on 2025-08-21 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0010_costumer_custumer_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costumer',
            name='quantiy_liter',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
