# Generated by Django 5.1.4 on 2025-08-21 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0011_alter_costumer_quantiy_liter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costumer',
            name='custumer_request',
            field=models.CharField(choices=[('Accept', 'Acept'), ('Reject', 'Reject'), ('Pending', 'Pending')], default='Pending', max_length=30),
        ),
    ]
