# Generated by Django 5.2.5 on 2025-08-23 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0012_alter_costumer_custumer_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milkman',
            name='addressline',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
