# Generated by Django 5.2.5 on 2025-08-23 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0013_alter_milkman_addressline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costumer',
            name='pic',
            field=models.URLField(blank=True, default=None, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='milkman',
            name='pic',
            field=models.URLField(blank=True, default=None, max_length=500, null=True),
        ),
    ]
