# Generated by Django 5.1.4 on 2025-08-25 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0014_alter_costumer_pic_alter_milkman_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now=True)),
                ('buyername', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=30)),
                ('sellerusername', models.CharField(max_length=30)),
                ('sellername', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
                ('pincode', models.IntegerField()),
                ('state', models.CharField(max_length=50)),
            ],
        ),
    ]
