# Generated by Django 5.1.4 on 2025-08-25 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0016_order_delivery_address_order_payment_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('pending', 'pending'), ('dispatch', 'dispatch'), ('on the way', 'on the way'), ('out for delivery', 'out for delivery'), ('cancel', 'cancel'), ('return', 'return')], default='pending', max_length=50),
        ),
    ]
