# Generated by Django 5.2.5 on 2025-08-25 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0017_order_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('pending', 'pending'), ('dispatch', 'dispatch'), ('on the way', 'on the way'), ('out for delivery', 'out for delivery'), ('delivered', 'delivered'), ('cancel', 'cancel'), ('return', 'return')], default='pending', max_length=50),
        ),
    ]
